version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: task-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-network

  app:
    build: .
    container_name: task-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskmanager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql
    networks:
      - task-network

volumes:
  mysql-data:

networks:
  task-network:
