version: '3.8'

services:
  app:
    build: .
    container_name: task-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:JCrOPdNMzELZXQOedGyljDZjraCyDjDL@yamanote.proxy.rlwy.net:36194/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: JCrOPdNMzELZXQOedGyljDZjraCyDjDL
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - task-network

networks:
  task-network:
